name: Versioning and Tagging
on:
  push:
    branches:
      - main
      - beta
jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Tagging dry run
      id: taggerDryRun
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
        PRERELEASE: true
        DRY_RUN: true

    - name: echo new tag / version
      run: |
        echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"

    - name: Tagging
      id: taggerFinal
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
        PRERELEASE: true
